### PR TITLE
Use latest eslint, up dependencies

### PR DESCRIPTION
**Pull request by tmathern**
## Description

License verification automation + Use latest eslint.

License list:
Screen Shot 2020-05-11 at 3 15 56 PM

Fixes # (issue)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by tmathern** [comment]
License flagged as Unknown is:
├─ valid-url@1.0.9
│  ├─ licenses: [1m[31mUNKNOWN[39m[22m
│  ├─ repository: https://github.com/ogt/valid-url
│  ├─ dependencyPath: /Users/mathern/Desktop/git/@adobe/cloud-blobstore-wrapper/node_modules/valid-url
│  ├─ path: /Users/mathern/Desktop/git/@adobe/cloud-blobstore-wrapper/node_modules/valid-url
│  └─ licenseFile: /Users/mathern/Desktop/git/@adobe/cloud-blobstore-wrapper/node_modules/valid-url/LICENSE

According to the repo, it is under MIT license: https://github.com/ogt/valid-url/blob/master/LICENSE

**Comment by alexkli** [comment]
Same comment as in https://github.com/adobe/asset-compute-sdk/pull/7#pullrequestreview-410289952 - I think we should move this into a CI job.

**Comment by DrGirlfriend** [comment]
The upping of the Azure SDK is going to take some refactoring as me and Jamie found when working with CloudStorage previously

**Comment by tmathern** [comment]
I'll close this for now, then.

**Pull request closed without merging**
